FROM python:3.8-slim-buster
WORKDIR app/
COPY . .
RUN ["pip3", "install", "-r" ,"requirements.txt"]

# Set environment variables for docker
ARG MAX_CONSIDERED_SUBREDDITS
ENV MAX_CONSIDERED_SUBREDDITS=${MAX_CONSIDERED_SUBREDDITS}

ARG MAX_SUBMISSIONS_PER_SUBREDDIT
ENV MAX_SUBMISSIONS_PER_SUBREDDIT=${MAX_SUBMISSIONS_PER_SUBREDDIT}

ARG MAX_COMMENTS_PER_SUBMISSION
ENV MAX_COMMENTS_PER_SUBMISSION=${MAX_COMMENTS_PER_SUBMISSION}

ARG CLIENT_SECRET
ENV CLIENT_SECRET=${CLIENT_SECRET}

ARG USER_AGENT
ENV USER_AGENT=${USER_AGENT}

ARG CLIENT_ID
ENV CLIENT_ID=${CLIENT_ID}

ARG SCHEDULE_INTERVAL
ENV SCHEDULE_INTERVAL=${SCHEDULE_INTERVAL}

ENTRYPOINT ["python", "run.py"]

